descriptions = new Array("Language Resources The World Wide Web is, for practical purposes, an endless source of information on technical subjects. It can sometimes be diff...",
	"Using this CD Welcome to the Programming Language Pragmatics, 2 nd Edition Companion CD. This page contains some information to help you get start...",
	"15: Code Improvement",
	"2.4: Theoretical Foundations",
	"3.4: Implementing Scope",
	"3.7: Separate Compilation",
	"4.5: Space Management for Attributes",
	"5.2.1: Computer Arithmetic",
	"5.4.4: Two Example Architectures: The x86 and MIPS",
	"6.5.4: Generators in Icon",
	"6.7: Nondeterminacy",
	"CD Sections Chapter 2 Programming Language Syntax 2.3.4 Syntax Errors 1-CD to 12-CD 2.4 Theoretical Foundations 13-CD to 20-CD Chapter 3 Names, Sc...",
	"7.2.4: The ML Type System",
	"7.3.3: With Statements",
	"7.9: Files and Input/Output",
	"8.2.1: Displays",
	"8.2.2: Case Studies: C on the MIPS; Pascal on the x86",
	"8.2.3: Register Windows",
	"8.3.2: Call by Name",
	"8.4.4: Generics in C++, Java, and C#",
	"8.6.3: Implementation of Iterators",
	"8.6.4: Discrete Event Simpulation",
	"9.5: Multiple Inheritance",
	"9.6.1: The Object Model of Smalltalk",
	"10.6: Theoretical Foundations",
	"11.3: Theoretical Foundations",
	"14.2: Intermediate Forms",
	"14.7: Dynamic Linking",
	"2.3.4: Syntax Errors",
	"To the best of my knowledge, no Euclid compilers are available for modern machines. The code in figure 3.9 has not been tested. ",
	"CPP = g++ main: main.cc foo.cc foo.h $(CPP) -o main main.cc foo.cc main_alt: main_alt.cc foo.cc foo.h $(CPP) -o main_alt main.cc foo.cc ",
	"first_word second_word third_word ",
	"this is the first line this is a line with a comment % that you can't see that was an all-blank line this latter part of the file will not be cons...",
	"This file has a line that begins with foo: foo found in second_file ",
	"This file has a line that begins with bar: bar found in third_file ",
	"now is the time for all good folk to come to the aid of the party ",
	"this is a test this is only a test if this had been real it would have been interesting ",
	"four score and seven is a lot but I forget exactly how many ",
	"Fleshing out the code of Example 6.71 is the task of Exercise 6.15. ",
	"Fleshing out the code of Example 6.74 is the task of Exercise 6.16. ",
	"The code in example 8.64 has not been tested. ",
	"Example 9.19: see code in example_9.9-12/gp_list.cc. ",
	"Examples 9.37 and 9.38: see code in example_9.31-34/person.cc. ",
	"Streams (Examples 10.26 and 10.27) don't work as shown in the book in Scheme because Scheme uses applicative order evaluation. They can be made to...",
	"See extended (full-game-playing) version in example_11.29. ",
	"Code Samples The directories below contain source code for most of the nontrivial code fragments in Programming Language Pragmatics, 2 nd edition....",
	"some preliminary text top-level title, on two lines some intermediate text 2nd-level title, on one line 3rd-level title more three titles on two l...",
	"some preliminary text top-level title, on two lines some intermediate text 2nd-level title, on one line 3rd-level title more three titles on two l...",
	"war and peace War And Peace through the looking glass Computer Organization: the hardware/software interface the eBay book ",
	"some preliminary text top-level title, on two lines some intermediate text 2nd-level title, on one line 3rd-level title more three titles on two l...",
	"First addend Second addend ",
	"First addend Second addend ",
	"First addend Second addend ",
	"Idefy the tyranny of precedent (Clara Barton). ",
	"",
	"some preliminary text top-level title, on two lines some intermediate text 2nd-level title, on one line 3rd-level title more three titles on two l...",
	"14.10: In More Depth Explorations, numbers 14.20 to 14.23",
	"3.10: In More Depth Explorations, numbers 3.34 to 3.38",
	"4.9: In More Depth Explorations, numbers 4.32 to 4.33",
	"5.8: In More Depth Explorations, numbers 5.35 to 5.37",
	"6.10: In More Depth Explorations, numbers 6.40 to 6.43",
	"7.13: In More Depth Explorations, numbers 7.46 to 7.48",
	"8.9: In More Depth Explorations, numbers 8.50 to 8.52",
	"9.9: In More Depth Explorations, numbers 9.35 to 9.37",
	"10.10: In More Depth Explorations, numbers 10.29 to 10.31",
	"11.7: In More Depth Explorations, numbers 11.26 to 11.29",
	"2.7: In More Depth Explorations, numbers 2.37 to 2.38",
	"CD Explorations Chapter 2 Programming Language Syntax Explorations 2.37 to 2.38 22-CD Chapter 3 Names, Scopes, and Bindings Explorations 3.34 to 3...",
	"14.9: In More Depth Exercises, numbers 14.12 to 14.14",
	"3.9: In More Depth Exercises, numbers 3.20 to 3.25",
	"CD Exercises Chapter 2 Programming Language Syntax Exercises 2.24 to 2.28 21-CD Chapter 3 Names, Scopes, and Bindings Exercises 3.20 to 3.25 36-CD...",
	"4.8: In More Depth Exercises, numbers 4.23 to 4.27",
	"5.7: In More Depth Exercises, numbers 5.16 to 5.23",
	"6.9: In More Depth Exercises, numbers 6.33 to 6.36",
	"7.12: In More Depth Exercises, numbers 7.33 to 7.37",
	"8.8: In More Depth Exercises, numbers 8.34 to 8.44",
	"9.8: In More Depth Exercises, numbers 9.19 to 9.29",
	"10.9: In More Depth Exercises, numbers 10.20 to 10.23",
	"11.6: In More Depth Exercises, numbers 11.18 to 11.20",
	"2.6: In More Depth Exercises, numbers 2.24 to 2.28",
	"1: Introduction",
	"1: Introduction",
	"1.1: The Art of Language Design",
	"1.1: The Art of Language Design",
	"1.1: The Art of Language Design",
	"1.2: The Programming Language Spectrum",
	"1.2: The Programming Language Spectrum",
	"1.2: The Programming Language Spectrum",
	"1.3: Why Study Programming Languages?",
	"1.3: Why Study Programming Languages?",
	"1.4: Compilation and Interpretation",
	"1.4: Compilation and Interpretation",
	"1.4: Compilation and Interpretation",
	"1.4: Compilation and Interpretation",
	"1.4: Compilation and Interpretation",
	"1.4: Compilation and Interpretation",
	"1.4: Compilation and Interpretation",
	"1.4: Compilation and Interpretation",
	"1.5: Programming Environments",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.6: An Overview of Compilation",
	"1.7: Summary and Concluding Remarks",
	"1.8: Exercises",
	"1.9: Explorations",
	"1.9: Explorations",
	"1.10: Bibliographic Notes",
	"2: Programming Language Syntax",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.1: Specifying Syntax: Regular Expressions and Context-Free Grammars",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.2: Scanning",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.3: Parsing",
	"2.4: Theoretical Foundations",
	"2.5: Summary and Concluding Remarks",
	"2.6: Exercises",
	"2.6: Exercises",
	"2.6: Exercises",
	"2.6: Exercises",
	"2.6: Exercises",
	"2.7: Explorations",
	"2.8: Bibliographic Notes",
	"3: Names, Scopes, and Bindings",
	"3.1: The Notion of Binding Time",
	"3.1: The Notion of Binding Time",
	"3.2: Object Lifetime and Storage Management",
	"3.2: Object Lifetime and Storage Management",
	"3.2: Object Lifetime and Storage Management",
	"3.2: Object Lifetime and Storage Management",
	"3.2: Object Lifetime and Storage Management",
	"3.2: Object Lifetime and Storage Management",
	"3.2: Object Lifetime and Storage Management",
	"3.2: Object Lifetime and Storage Management",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.3: Scope Rules",
	"3.4: Implementing Scope",
	"3.5: The Binding of Referencing Environments",
	"3.5: The Binding of Referencing Environments",
	"3.5: The Binding of Referencing Environments",
	"3.5: The Binding of Referencing Environments",
	"3.5: The Binding of Referencing Environments",
	"3.5: The Binding of Referencing Environments",
	"3.6: Binding Within a Scope",
	"3.6: Binding Within a Scope",
	"3.6: Binding Within a Scope",
	"3.6: Binding Within a Scope",
	"3.6: Binding Within a Scope",
	"3.6: Binding Within a Scope",
	"3.6: Binding Within a Scope",
	"3.7: Seperate Complilation",
	"3.8: Summary and Concluding Remarks",
	"3.9: Exercises",
	"3.9: Exercises",
	"3.9: Exercises",
	"3.9: Exercises",
	"3.9: Exercises",
	"3.9: Exercises",
	"3.10: Explorations",
	"3.11: Bibliographic Notes",
	"3.11: Bibliographic Notes",
	"4: Semantic Analysis",
	"4.1: The Role of the Semantic Analyzer",
	"4.1: The Role of the Semantic Analyzer",
	"4.1: The Role of the Semantic Analyzer",
	"4.1: The Role of the Semantic Analyzer",
	"4.2: Attribute Grammars",
	"4.2: Attribute Grammars",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.3: Evaluating Attributes",
	"4.4: Action Routines",
	"4.4: Action Routines",
	"4.5: Space Management for Attributes",
	"4.6: Decorating a Syntax Tree",
	"4.6: Decorating a Syntax Tree",
	"4.6: Decorating a Syntax Tree",
	"4.6: Decorating a Syntax Tree",
	"4.6: Decorating a Syntax Tree",
	"4.7: Summary and Concluding Remarks",
	"4.7: Summary and Concluding Remarks",
	"4.8: Exercises",
	"4.8: Exercises",
	"4.8: Exercises",
	"4.8: Exercises",
	"4.9: Explorations",
	"4.10: Bibliographic Notes",
	"5: Target Machine Architecture",
	"5.1: The Memory Hierarchy",
	"5.1: The Memory Hierarchy",
	"5.1: The Memory Hierarchy",
	"5.2: Data Representation",
	"5.2: Data Representation",
	"5.3: Instruction Set Architecture",
	"5.3: Instruction Set Architecture",
	"5.3: Instruction Set Architecture",
	"5.4: Architecture and Implementation",
	"5.4: Architecture and Implementation",
	"5.4: Architecture and Implementation",
	"5.4: Architecture and Implementation",
	"5.4: Architecture and Implementation",
	"5.4: Architecture and Implementation",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.5: Compiling for Modern Processors",
	"5.6: Summary and Concluding Remarks",
	"5.6: Summary and Concluding Remarks",
	"5.7: Exercises",
	"5.7: Exercises",
	"5.7: Exercises",
	"5.8: Explorations",
	"5.9: Bibliographic Notes",
	"5.9: Bibliographic Notes",
	"6: Control Flow",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.1: Expression Evaluation",
	"6.2: Structured and Unstructured Flow",
	"6.2: Structured and Unstructured Flow",
	"6.2: Structured and Unstructured Flow",
	"6.2: Structured and Unstructured Flow",
	"6.2: Structured and Unstructured Flow",
	"6.2: Structured and Unstructured Flow",
	"6.3: Sequencing",
	"6.4: Selection",
	"6.4: Selection",
	"6.4: Selection",
	"6.4: Selection",
	"6.4: Selection",
	"6.4: Selection",
	"6.4: Selection",
	"6.4: Selection",
	"6.4: Selection",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.5: Iteration",
	"6.6: Recursion",
	"6.6: Recursion",
	"6.6: Recursion",
	"6.6: Recursion",
	"6.6: Recursion",
	"6.6: Recursion",
	"6.6: Recursion",
	"6.6: Recursion",
	"6.7: Nondeterminacy",
	"6.8: Summary and Concluding Remarks",
	"6.8: Summary and Concluding Remarks",
	"6.9: Exercises",
	"6.9: Exercises",
	"6.9: Exercises",
	"6.9: Exercises",
	"6.9: Exercises",
	"6.9: Exercises",
	"6.10: Explorations",
	"6.11: Bibliographic Notes",
	"6.11: Bibliographic Notes",
	"7: Data Types",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.1: Type Systems",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.2: Type Checking",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.3: Records (Structures) and Variants (Unions)",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.4: Arrays",
	"7.5: Strings",
	"7.6: Sets",
	"7.6: Sets",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.7: Pointers and Recursive Types",
	"7.8: Lists",
	"7.8: Lists",
	"7.8: Lists",
	"7.9: Files and Input/Output",
	"7.10: Equality Testing and Assignment",
	"7.10: Equality Testing and Assignment",
	"7.11: Summary and Concluding Remarks",
	"7.11: Summary and Concluding Remarks",
	"7.11: Summary and Concluding Remarks",
	"7.12: Exercises",
	"7.12: Exercises",
	"7.12: Exercises",
	"7.12: Exercises",
	"7.12: Exercises",
	"7.12: Exercises",
	"7.13: Explorations",
	"7.14: Bibliographic Notes",
	"7.14: Bibliographic Notes",
	"8: Subroutines and Control Abstraction",
	"8.1: Review of Stack Layout",
	"8.1: Review of Stack Layout",
	"8.2: Calling Sequences",
	"8.2: Calling Sequences",
	"8.2: Calling Sequences",
	"8.2: Calling Sequences",
	"8.2: Calling Sequences",
	"8.2: Calling Sequences",
	"8.2: Calling Sequences",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.3: Parameter Passing",
	"8.4: Generic Subroutines and Modules",
	"8.4: Generic Subroutines and Modules",
	"8.4: Generic Subroutines and Modules",
	"8.4: Generic Subroutines and Modules",
	"8.4: Generic Subroutines and Modules",
	"8.4: Generic Subroutines and Modules",
	"8.4: Generic Subroutines and Modules",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.5: Exception Handling",
	"8.6: Coroutines",
	"8.6: Coroutines",
	"8.6: Coroutines",
	"8.6: Coroutines",
	"8.6: Coroutines",
	"8.6: Coroutines",
	"8.7: Summary and Concluding Remarks",
	"8.8: Exercises",
	"8.8: Exercises",
	"8.8: Exercises",
	"8.8: Exercises",
	"8.8: Exercises",
	"8.8: Exercises",
	"8.9: Explorations",
	"8.10: Bibliographic Notes",
	"8.10: Bibliographic Notes",
	"9: Data Abstraction and Object Orientation",
	"9: Data Abstraction and Object Orientation",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.1: Object-Oriented Programming",
	"9.2: Encapsulation and Inheritance",
	"9.2: Encapsulation and Inheritance",
	"9.2: Encapsulation and Inheritance",
	"9.2: Encapsulation and Inheritance",
	"9.2: Encapsulation and Inheritance",
	"9.2: Encapsulation and Inheritance",
	"9.2: Encapsulation and Inheritance",
	"9.2: Encapsulation and Inheritance",
	"9.3: Initialization and Finalization",
	"9.3: Initialization and Finalization",
	"9.3: Initialization and Finalization",
	"9.3: Initialization and Finalization",
	"9.3: Initialization and Finalization",
	"9.3: Initialization and Finalization",
	"9.3: Initialization and Finalization",
	"9.3: Initialization and Finalization",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.4: Dynamic Method Binding",
	"9.5: Multiple Inheritance",
	"9.6: Object-Oriented Programming Revisited",
	"9.7: Summary and Concluding Remarks",
	"9.7: Summary and Concluding Remarks",
	"9.8: Exercises",
	"9.8: Exercises",
	"9.9: Explorations",
	"9.10: Bibliographic Notes",
	"10: Functional Languages",
	"10.1: Historical Origins",
	"10.1: Historical Origins",
	"10.2: Functional Programming Concepts",
	"10.2: Functional Programming Concepts",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.3: A Review/Overview of Scheme",
	"10.4: Evaluation Order Revisited",
	"10.4: Evaluation Order Revisited",
	"10.4: Evaluation Order Revisited",
	"10.4: Evaluation Order Revisited",
	"10.4: Evaluation Order Revisited",
	"10.4: Evaluation Order Revisited",
	"10.5: Higher-Order Functions",
	"10.5: Higher-Order Functions",
	"10.5: Higher-Order Functions",
	"10.5: Higher-Order Functions",
	"10.6: Theoretical Foundations",
	"10.7: Functional Programming in Perspective",
	"10.7: Functional Programming in Perspective",
	"10.8: Summary and Concluding Remarks",
	"10.9: Exercises",
	"10.9: Exercises",
	"10.9: Exercises",
	"10.9: Exercises",
	"10.10: Explorations",
	"10.11: Bibliographic Notes",
	"11: Logic Languages",
	"11.1: Logic Programming Concepts",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.2: Prolog",
	"11.3: Theoretical Foundations",
	"11.4: Logic Programming in Perspective",
	"11.4: Logic Programming in Perspective",
	"11.4: Logic Programming in Perspective",
	"11.5: Summary and Concluding Remarks",
	"11.6: Exercises",
	"11.6: Exercises",
	"11.7: Explorations",
	"11.8: Bibliographic Notes",
	"12: Concurrency",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.1: Background and Motivation",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.2: Concurrent Programming Fundamentals",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.3: Shared Memory",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.4: Message Passing",
	"12.5: Summary and Concluding Remarks",
	"12.5: Summary and Concluding Remarks",
	"12.6: Exercises",
	"12.6: Exercises",
	"12.6: Exercises",
	"12.6: Exercises",
	"12.6: Exercises",
	"12.6: Exercises",
	"12.7: Explorations",
	"12.8: Bibliographic Notes",
	"12.8: Bibliographic Notes",
	"13: Scripting Languages",
	"13.1: What Is a Scripting Language?",
	"13.1: What Is a Scripting Language?",
	"13.1: What Is a Scripting Language?",
	"13.1: What Is a Scripting Language?",
	"13.1: What Is a Scripting Language?",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.2: Problem Domains",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.3: Scripting the World Wide Web",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.4: Innovative Features",
	"13.5: Summary and Concluding Remarks",
	"13.5: Summary and Concluding Remarks",
	"13.6: Exercises",
	"13.6: Exercises",
	"13.6: Exercises",
	"13.6: Exercises",
	"13.6: Exercises",
	"13.7: Explorations",
	"13.8: Bibliographic Notes",
	"13.8: Bibliographic Notes",
	"14: Building a Runnable Program",
	"14.1: Back-End Compiler Structure",
	"14.1: Back-End Compiler Structure",
	"14.1: Back-End Compiler Structure",
	"14.1: Back-End Compiler Structure",
	"14.2: Intermediate Forms",
	"14.2: Intermediate Forms",
	"14.2: Intermediate Forms",
	"14.3: Code Generation",
	"14.3: Code Generation",
	"14.3: Code Generation",
	"14.3: Code Generation",
	"14.3: Code Generation",
	"14.3: Code Generation",
	"14.4: Address Space Organization",
	"14.5: Assembly",
	"14.5: Assembly",
	"14.5: Assembly",
	"14.5: Assembly",
	"14.5: Assembly",
	"14.6: Linking",
	"14.6: Linking",
	"14.6: Linking",
	"14.7: Dynamic Linking",
	"14.7: Dynamic Linking",
	"14.8: Summary and Concluding Remarks",
	"14.9: Exercises",
	"14.9: Exercises",
	"14.10: Explorations",
	"14.11: Bibliographic Notes",
	"15: Code Improvement",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"A: Programming Languages Mentioned",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Bibliography",
	"Chapter Navigation Click on the book icons to show or hide the contents of each chapter. You can also use the Expand All / Collapse All buttons to...");